# Generated by Django 3.1.5 on 2021-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
